apiVersion: v1
kind: Template
labels:
  template: f8a-api-gateway
metadata:
  name: f8a-api-gateway
  annotations:
    description: f8a-api-gateway
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: f8a-api-gateway
    name: f8a-api-gateway
  spec:
    selector:
      service: f8a-api-gateway
    template:
      metadata:
        labels:
          service: f8a-api-gateway
      spec:
        containers:
        - env:
          - name: DEPLOYMENT_PREFIX
            valueFrom:
              configMapKeyRef:
                name: bayesian-config
                key: deployment-prefix
          - name: BAYESIAN_FETCH_PUBLIC_KEY
            valueFrom:
              configMapKeyRef:
                name: bayesian-config
                key: keycloak-url
          - name: BAYESIAN_JWT_AUDIENCE
            value: "fabric8-online-platform,openshiftio-public"
          - name: USER_WHITELIST
            value: ${USER_WHITELIST}
          - name: FLASK_LOGGING_LEVEL
            value: ${FLASK_LOGGING_LEVEL}
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: f8a-api-gateway
          ports:
          - containerPort: 5000
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 10
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    replicas: ${{REPLICAS}}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: f8a-api-gateway
    name: f8a-api-gateway
  spec:
    ports:
    - name: "32000"
      port: 32000
      protocol: TCP
      targetPort: 5000
    selector:
      service: f8a-api-gateway
- apiVersion: v1
  kind: Route
  metadata:
    name: f8a-api-gateway
  spec:
    host:
    to:
      kind: Service
      name: f8a-api-gateway
parameters:
- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "registry.devshift.net"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "fabric8-analytics/f8a-api-gateway"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"

- description: Number of deployment replicas
  displayName: Number of deployment replicas
  required: true
  name: REPLICAS
  value: "1"

- description: "Flask logging level (see: https://docs.python.org/3/library/logging.html#levels)"
  displayName: Flask logging level
  required: false
  name: FLASK_LOGGING_LEVEL
  value: "INFO"

- description: A comma-separated list of whitelisted users that are allowed to use the service
  displayName: User whitelist
  required: true
  name: USER_WHITELIST
  value: "msrb,thrcka,macermak,pkajaba"
